version: '3.1'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
    ports:
      - '80:80'
    container_name: nginx

  server8:
    image: node:16-alpine3.11
    working_dir: /home/app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - PORT=8000
      - MSG=User
    volumes:
      - ./app:/home/app
    ports:
      - 8000:8000
    command: >
      node index.js
  
  server9:
    image: node:16-alpine3.11
    working_dir: /home/app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - PORT=9000
      - MSG=Admin
    volumes:
      - ./app:/home/app
    ports:
      - 9000:9000
    command: >
      node index.js

  server3:
    image: node:16-alpine3.11
    working_dir: /home/app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - PORT=3000
      - MSG=Test
    volumes:
      - ./app:/home/app
    ports:
      - 3000:3000
    command: >
      node index.js
